version: 1.0.{build}
branches:
  only:
  - blueprint
  - master
skip_tags: true
image: Visual Studio 2017
clone_depth: 5

environment:
  GITHUB_TOKEN:
    secure: P9vqC9cj6b1nR/LWOAdtqKKBc5jBxwVX42Fzn924FsVLYblv954UV73WO1q+57aC
  REPO_SLUG: vicr123/entertaining-chess
  deploy_project: entertaining-chess
  deploy_version: ''
  deploy_artifact: ''
    
build_script:
- cmd: >-
    appveyor\build.bat

test: off

artifacts:
- path: deploy
  name: entertaining-chess-Windows
  
  
before_deploy:
- ps:
    iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/deploy.ps1'))
    
deploy_script:
- ps: >-
    
    Start-FileDownload 'https://github.com/probonopd/uploadtool/raw/master/upload.sh'
    
    sh -c "TRAVIS_BRANCH=$env:APPVEYOR_REPO_BRANCH TRAVIS_COMMIT=$env:APPVEYOR_REPO_BRANCH ./upload.sh /c/projects/entertaining-chess/entertaining-chess-Windows.zip 2>/dev/null"
